[package]
name = "solana-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "2.0.5"
bs58 = "0.5.1"
dotenvy = "0.15.7"
serde_json = "1.0.125"
solana-client = "2.0.5"
tokio = { version = "1.39.2", features = ["full"] }
clap = { version = "4.5.4", features = ["derive"] }
